### ISSUE TITLE
Problem with reconnect, if Internet lost

### ISSUE THREAD

**Issue by rtprof** [philbowles/PangolinMQTT#35]
Hello. I use the latest version (1.0.1) and have the problem with reconnect.
I blocked an Internet access for the esp8266 and after few minutes opened it

> D:1: CONNECTING to m16.cloudmqtt.com:15381 as esp8266-E48296 FH=14832 session=1
14:02:35.092 -> D:4: We are now clean:)
14:02:35.092 -> D:2: ----> TX CONNECT 95 bytes
14:02:35.264 -> Address: 0x3FFF35FC len: 0x5F (95)
14:02:35.264 -> [0x3FFF35FC] 0x00000000: ************ some data
************ some data
14:02:35.300 -> [0x3FFF364C] 0x00000050: 64 00 0C 62 42 4E 62 76 57 78 75 64 66 36 65      d..bBNbvWxudf6e
14:02:35.438 -> D:4: <---- RX CONNACK 3FFF6F6A len=4
14:02:35.472 -> Address: 0x3FFF6F6A len: 0x4 (4)
14:02:35.472 -> [0x3FFF6F6A] 0x00000000: 20 02 00 00 ...
14:02:35.472 -> D:2: <---- RX CONNACK 3FFF6F6A len=4
14:02:35.472 -> Address: 0x3FFF6F6A len: 0x4 (4)
14:02:35.472 -> [0x3FFF6F6A] 0x00000000: 20 02 00 00 ...
14:02:35.472 -> D:1: CONNECTED FH=14832 MaxPL=5368 SESSION CLEAN
14:02:35.472 -> Connected to MQTT.
14:02:35.472 -> Session present: 0
14:02:36.769 -> D:1: T=2880731 SRV GONE? ka=30 tix=46
14:02:59.531 -> D:1: ON DISCONNECT FH=11624 r=1
14:02:59.531 -> D:4: CLEAR 0 FRAGMENTS
14:02:59.531 -> Disconnected from MQTT.
14:03:00.828 -> D:1: TCP CHOPPED US!
14:03:21.288 -> D:1: ON DISCONNECT FH=14832 r=0
14:03:21.288 -> D:4: CLEAR 0 FRAGMENTS
14:03:21.288 -> Disconnected from MQTT.

**Comment by poulch74** [comment]
https://github.com/philbowles/PangolinMQTT/issues/33

**Comment by philbowles** [comment]
This should be fixed by v2

**Comment by Wollwolke** [comment]
Unfortunately, I still have the problem with v2. Even after redownload ESPAsyncTCP and Pangolin. I tried to get the Quickstart Example with a reconnect delay of over 30s to work, but the result is the same as rtprof's.

**Comment by AcuarioCat** [comment]
I'm also having reconnect problems after loss of internet. On previous versions it worked ok. I get disconnect reasons of 8 and 9 when trying to reconnect. Rebooting reconnects correctly.

**Comment by HamzaHajeir** [comment]
If any need, all can checkout this Pangolin-based fork [H4AsyncMQTT](https://github.com/hamzahajeir/h4asyncmqtt).
